Dev
EvgeniyKozenok/frame pull request #1
Opened 2017-03-18 02:24 UTC by EvgeniyKozenok

Application, Router, Request, Render, Controller, Logger created

2017-03-20 09:06 UTC, Artiomtb commented on src/Application.php
> +            $this->logger->log($e->getMessage());
Хорошо бы для логгера сделать отдельные методы по уровню, например, info, warning, error, fatal и т.д.

2017-03-20 09:07 UTC, Artiomtb commented on src/Application.php
> +    private function debug($o)
Ты только в Application это используешь?

У тебя же, кстати, есть логгер.

2017-03-20 09:08 UTC, Artiomtb commented on src/Controller/BaseController.php
> +use john\frame\Render\Render;
По конвенции все элементы неймспейса должны быть с Большой буквы

2017-03-20 09:09 UTC, Artiomtb commented on src/Logger/Logger.php
> +    public static $PATH;
Лучше юзать через статический метод setPath, а поле делать private

2017-03-20 09:10 UTC, Artiomtb commented on src/Logger/Logger.php
> +    public function __construct(string $name, string $file = null)
Было бы прикольно в логгере делать опции out: в файл или через echo в html... но это на будущее

2017-03-20 09:10 UTC, EvgeniyKozenok commented on src/Application.php
> +    private function debug($o)
Это просто для дэбага, его не нужно в Application в принципе, немного недоглядел при отправке

2017-03-20 09:11 UTC, EvgeniyKozenok commented on src/Controller/BaseController.php
> +use john\frame\Render\Render;
Ок, поправлю

2017-03-20 09:11 UTC, Artiomtb commented on src/Render/Render.php
> +        $loader = new Twig_Loader_Filesystem($_SERVER['DOCUMENT_ROOT'] . '/../src/views');
Плохо-плохо. Всю инициализацию надо делать один раз в Application. У тебя могут рендерится за раз несколько вьюх, зачем все заново для каждой?

В этом методе оставь только сам вызов рендера, а как прокинуть туда $twig - подумай.

2017-03-20 09:13 UTC, Artiomtb commented on src/Request/Request.php
> +class Request
Чтобы поверил, что не копипаст - сделай универсальный метод getParameter($name), который вернет значение параметра, в каком виде бы он не пришел - $_GET, $_POST, php:://input  в виде json и т.д.

2017-03-20 09:15 UTC, Artiomtb requested changes
Исправляй замечания.

2017-03-20 18:06 UTC, ddavidov requested changes
Reviewed

2017-03-20 18:06 UTC, ddavidov commented on src/Application.php
> +            $this->logger->log($e->getMessage());
+

2017-03-20 18:06 UTC, ddavidov commented on src/Render/Render.php
> +class Render
*Renderer

2017-03-20 18:06 UTC, ddavidov commented on src/Render/Render.php
> +use Twig_Environment;
По поводу этих вот вещей. Запомни плз. пока это место. Тут не совсем верный подход, мы там будем говорить почему и как это разрулить. Пока ничего не меняй просто запомни это место.

2017-03-20 18:06 UTC, ddavidov commented on src/Render/Render.php
> +        return $this->rendered;
Логика есть. А смогёшь объяснить почему именно так сделал?) (Почему отдельным методом сделал getRenderd())

2017-03-20 18:06 UTC, ddavidov commented on src/Request/Request.php
> +    public function getQueryParams(): string
А это зачем метод? Назначение?

2017-03-20 23:55 UTC, EvgeniyKozenok commented on src/Request/Request.php
> +    public function getQueryParams(): string
Так реализовал вот это твое задани:
По пунктам, что вам нужно помнить из незаконченного:
1. Класс Request:  Добавить методы получения (фильтрации) параметров запроса (query string) (Чтоб например, я мог в контроллере echo $request->getQueryParams('aaa'); и оно вернёт вернет этот параметр со значением, если параметр не указан, вернет все переданные параметры с соответсвующими значениями)

2017-03-20 23:55 UTC, EvgeniyKozenok commented on src/Render/Render.php
> +use Twig_Environment;
Ок, жду среду

2017-03-20 23:56 UTC, EvgeniyKozenok commented on src/Render/Render.php
> +class Render
Поправил

2017-03-21 00:07 UTC, EvgeniyKozenok commented on src/Render/Render.php
> +        return $this->rendered;
Так это ж как бы это обычный геттер для приватного поля класса, в котором хранится отрендеренный шаблон  для дальнейшей передачи его в response  в виде контента.

2017-03-21 00:46 UTC, EvgeniyKozenok commented on src/Request/Request.php
> +class Request
Артем а чем мой метод getQueryParams() не подходит, я его для этого и задумывал: по умолчанию ин возвращает все параметры из массива $_REQUEST, если ему передлать имя то он вернет параметр по имени со значением или я что-то не до конца понимаю, что требуется?

2017-03-21 00:46 UTC, EvgeniyKozenok commented on src/Render/Render.php
> +        $loader = new Twig_Loader_Filesystem($_SERVER['DOCUMENT_ROOT'] . '/../src/views');
Сделал

2017-03-21 00:46 UTC, EvgeniyKozenok commented on src/Logger/Logger.php
> +    public static $PATH;
ок

2017-03-21 08:36 UTC, ddavidov commented on src/Request/Request.php
> +    public function getQueryParams(): string
Ну ок, но блин, сложновата реализация...

2017-03-21 08:49 UTC, EvgeniyKozenok commented on src/Request/Request.php
> +    public function getQueryParams(): string
Так сказали ж не копипастить, вот и придумал так )

2017-03-21 10:44 UTC, Artiomtb commented on src/Request/Request.php
> +class Request
попробуй отправить такой запрос:

```
curl -H "Content-Type: application/json" -X POST -d '{"username":"admin","password":"pass"}' http://<url фреймворка>
```
Как мне получить значение username и password?

2017-03-21 10:47 UTC, Artiomtb requested changes
Смотри ещё)

2017-03-21 10:47 UTC, Artiomtb commented on src/Logger/Logger.php
> +    public function log(int $level = 100, string $message)
можно и так, но лучше отдельные методы info, warn, debug, ...

2017-03-21 10:47 UTC, Artiomtb commented on src/Logger/Logger.php
> +    public function debug($message)
А, если есть, то просто их и вызывай, а то в Applicationу тебя вызов log. А log вообще можно убрать или сделать приватным.

2017-03-21 10:47 UTC, Artiomtb commented on src/Request/Request.php
> +        echo "<pre>";
дебаг инфу удаляем.

2017-03-21 10:47 UTC, Artiomtb commented on src/Service/ServiceContainer.php
> +class ServiceContainer
мб сделать синглтоном?

2017-03-21 17:05 UTC, EvgeniyKozenok commented on src/Logger/Logger.php
> +    public function debug($message)
Поправил

2017-03-21 17:05 UTC, EvgeniyKozenok commented on src/Service/ServiceContainer.php
> +class ServiceContainer
Ага, как то сразу и не подумал

2017-04-02 08:16 UTC, Artiomtb approved these changes
Approved.

2017-04-02 11:59 UTC, merged